// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncApp26.Infrastructure.Context;

#nullable disable

namespace SyncApp26.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721133750_AddSignatureRecords")]
    partial class AddSignatureRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SyncApp26.Domain.Entities.DataChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedChangesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByAdminId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("DataChangeRequests");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.DepartmentFunction", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("DepartmentFunctions");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.DocumentSignatureToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PeriodicTrainingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentSignatureTokens");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.Function", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.ImportHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportHistories");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.PeriodicTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DurationHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorSignatureMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialTaught")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRowId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierSignatureMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserDocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("PeriodicTrainings");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.SignatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DurationHoursSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegacyUnverified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialTaughtSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PeriodicTrainingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHmac")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerFullNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerPositionSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SignerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrainingDateSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserDocumentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodicTrainingId");

                    b.HasIndex("UserDocumentId")
                        .HasDatabaseName("IX_SignatureRecords_UserDocumentId");

                    b.HasIndex("SignerUserId", "SignedAt")
                        .HasDatabaseName("IX_SignatureRecords_SignerUserId_SignedAt");

                    b.ToTable("SignatureRecords");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmittedByFunction")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmittedByName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BadgeNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommuteDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommuteRoute")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FunctionId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsEmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualifications")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Users_DeletedAt");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("FunctionId");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "DeletedAt")
                        .HasDatabaseName("IX_Users_DepartmentId_DeletedAt");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImportHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserChangeHistories");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminCryptographicSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminSignatureIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminSignatureMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdminSignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerCryptographicSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerSignatureIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerSignatureMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ManagerSignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCryptographicSignature")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UserSignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserInitialTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorSignatureMethod")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroductoryTrainingContent")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IntroductoryTrainingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntroductoryTrainingHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntroductoryTrainingInstructor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroductoryTrainingInstructorFunction")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSignatureMethod")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierSignatureData")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifierSignatureMethod")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceTrainingContent")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WorkplaceTrainingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkplaceTrainingHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkplaceTrainingInstructor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceTrainingInstructorFunction")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkplaceTrainingLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DocumentType")
                        .IsUnique()
                        .HasDatabaseName("IX_UserInitialTrainings_UserId_DocumentType");

                    b.ToTable("UserInitialTrainings");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptographicProof")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSignatures_UserId");

                    b.ToTable("UserSignatures");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserSignatureHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptographicProof")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedByEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserSignatureHistories_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSignatureHistories_UserId");

                    b.ToTable("UserSignatureHistories");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.DataChangeRequest", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.User", "ResolvedByAdmin")
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.DepartmentFunction", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.Department", "Department")
                        .WithMany("DepartmentFunctions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncApp26.Domain.Entities.Function", "Function")
                        .WithMany("DepartmentFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.PeriodicTraining", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.UserDocument", "Document")
                        .WithMany()
                        .HasForeignKey("UserDocumentId");

                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany("PeriodicTrainings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.SignatureRecord", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.PeriodicTraining", "PeriodicTraining")
                        .WithMany()
                        .HasForeignKey("PeriodicTrainingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SyncApp26.Domain.Entities.User", "SignerUser")
                        .WithMany()
                        .HasForeignKey("SignerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SyncApp26.Domain.Entities.UserDocument", "UserDocument")
                        .WithMany()
                        .HasForeignKey("UserDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodicTraining");

                    b.Navigation("SignerUser");

                    b.Navigation("UserDocument");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.User", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.User", "AssignedTo")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SyncApp26.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SyncApp26.Domain.Entities.Function", "Function")
                        .WithMany("Users")
                        .HasForeignKey("FunctionId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Department");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserChangeHistory", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.ImportHistory", "ImportHistory")
                        .WithMany()
                        .HasForeignKey("ImportHistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserDocument", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserInitialTraining", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany("InitialTrainings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserSignature", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.UserSignatureHistory", b =>
                {
                    b.HasOne("SyncApp26.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentFunctions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.Function", b =>
                {
                    b.Navigation("DepartmentFunctions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SyncApp26.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("InitialTrainings");

                    b.Navigation("PeriodicTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
